apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../app
  - ../base

configMapGenerator:
  - name: k8s-golive-monitor
    namespace: k8s-golive-monitor
    files:
      - config.yaml
