apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-golive-monitor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-golive-monitor.labels" . | nindent 4 }}
data:
  {{- with .Values.golive.config }}
  config.yaml: |
    {{ toYaml . | nindent 4 }}
  {{- end }}
