{{- if or .Values.golive.auth.username .Values.golive.auth.token }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "k8s-golive-monitor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-golive-monitor.labels" . | nindent 4 }}
data:
  {{- if .Values.golive.auth.username }}
  username: {{ .Values.golive.auth.username | b64enc }}
  {{ end }}
  {{- if .Values.golive.auth.password }}
  password: {{ .Values.golive.auth.password | b64enc }}
  {{ end }}
  {{- if .Values.golive.auth.token }}
  token: {{ .Values.golive.auth.token | b64enc }}
  {{ end }}
  {{- with .Values.golive.config }}
  config.yaml: |
    {{ toYaml . | nindent 4 }}
  {{- end }}
{{ end }}
