apiVersion: v1
kind: Namespace
metadata:
  annotations:
    name: k8s-golive-monitor
  labels:
    app: k8s-golive-monitor
  name: k8s-golive-monitor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-golive-monitor
  labels:
    app: k8s-golive-monitor
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "apps"
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-golive-monitor
  labels:
    app: k8s-golive-monitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-golive-monitor
subjects:
  - kind: ServiceAccount
    name: k8s-golive-monitor
    namespace: k8s-golive-monitor
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-golive-monitor
  namespace: k8s-golive-monitor
  labels:
    app: k8s-golive-monitor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-golive-monitor
  namespace: k8s-golive-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-golive-monitor
  template:
    metadata:
      labels:
        app: k8s-golive-monitor
    spec:
      serviceAccountName: k8s-golive-monitor
      containers:
        - name: app
          image: apwide/k8s-golive-monitor:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - mountPath: /etc/golive/config.yaml
              name: config
              subPath: config.yaml
              readOnly: true
      volumes:
        - name: config
          configMap:
            defaultMode: 511
            name: k8s-golive-monitor
            optional: false
