apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-golive-monitor
  labels:
    app: k8s-golive-monitor
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "apps"
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "batch"
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-golive-monitor
  labels:
    app: k8s-golive-monitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-golive-monitor
subjects:
  - kind: ServiceAccount
    name: k8s-golive-monitor
    namespace: k8s-golive-monitor
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-golive-monitor
  namespace: k8s-golive-monitor
  labels:
    app: k8s-golive-monitor
