name: Build

on:
  workflow_dispatch:

  push:
    branches-ignore:
      - gh-pages
#    branches:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # important parameter

      - id: configure-git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - id: setup-helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.0

      - id: install-unittest
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest.git

      - id: test
        run: |
          helm unittest ./charts/k8s-golive-agent

      - id: release
        uses: helm/chart-releaser-action@v1.6.0
        if: ${{ github.ref == 'refs/heads/main' }}
#        with:
#          charts_dir: deployments/charts/k8s-golive-agent
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_GENERATE_RELEASE_NOTES: false
#
#      - name: Deploy to Pages
#        uses: peaceiris/actions-gh-pages@v4
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./public
